//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcdemo.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Invno { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
